[package]
name = "studycycle_api_routes"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lib]
doctest = false
test = false

[lints]
workspace = true

[features]
default = []

[dependencies]
studycycle_api = { workspace = true }
studycycle_api_crud = { workspace = true }
studycycle_utils = { workspace = true }
studycycle_routes = { workspace = true }
actix-web = { workspace = true }
