[package]
name = "studycycle_api_common"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "studycycle_api_common"
path = "src/lib.rs"
doctest = false
test = false

[lints]
workspace = true

[features]
full = []
ts-rs = [
  "studycycle_utils/ts-rs",
  "studycycle_db_schema/ts-rs",
  "studycycle_db_schema_file/ts-rs",
  "studycycle_db_views_comment/ts-rs",
  "studycycle_db_views_community/ts-rs",
  "studycycle_db_views_community_follower/ts-rs",
  "studycycle_db_views_community_follower_approval/ts-rs",
  "studycycle_db_views_community_moderator/ts-rs",
  "studycycle_db_views_custom_emoji/ts-rs",
  "studycycle_db_views_notification/ts-rs",
  "studycycle_db_views_local_image/ts-rs",
  "studycycle_db_views_local_user/ts-rs",
  "studycycle_db_views_modlog/ts-rs",
  "studycycle_db_views_person/ts-rs",
  "studycycle_db_views_person_content_combined/ts-rs",
  "studycycle_db_views_person_liked_combined/ts-rs",
  "studycycle_db_views_person_saved_combined/ts-rs",
  "studycycle_db_views_post/ts-rs",
  "studycycle_db_views_private_message/ts-rs",
  "studycycle_db_views_registration_applications/ts-rs",
  "studycycle_db_views_report_combined/ts-rs",
  "studycycle_db_views_site/ts-rs",
  "studycycle_db_views_vote/ts-rs",
]

[dependencies]
studycycle_utils.workspace = true
studycycle_db_schema.workspace = true
studycycle_db_schema_file.workspace = true
studycycle_db_views_comment.workspace = true
studycycle_db_views_community.workspace = true
studycycle_db_views_community_follower.workspace = true
studycycle_db_views_community_follower_approval.workspace = true
studycycle_db_views_community_moderator.workspace = true
studycycle_db_views_custom_emoji.workspace = true
studycycle_db_views_notification.workspace = true
studycycle_db_views_local_image.workspace = true
studycycle_db_views_local_user.workspace = true
studycycle_db_views_modlog.workspace = true
studycycle_db_views_person.workspace = true
studycycle_db_views_person_content_combined.workspace = true
studycycle_db_views_person_liked_combined.workspace = true
studycycle_db_views_person_saved_combined.workspace = true
studycycle_db_views_post_comment_combined.workspace = true
studycycle_db_views_post.workspace = true
studycycle_db_views_private_message.workspace = true
studycycle_db_views_registration_applications.workspace = true
studycycle_db_views_report_combined.workspace = true
studycycle_db_views_site.workspace = true
studycycle_db_views_vote.workspace = true
studycycle_diesel_utils.workspace = true
